### ISSUE TITLE
Unit Test Migration File Tracker

### ISSUE THREAD

**Issue by schodge** [ggventurini/python-deltasigma#32]
Files that have had tests moved to separate file in /tests/ folder:
- [x] _axisLabels.py (PR #31)
- [x] _bilogplot.py
- [x] _bplogsmooth.py
- [x] _bquantize.py
- [x] _bunquantize.py
- [x] _calculateSNR.py
- [x] _calculateTF.py
- [x] _cancelPZ.py
-  _changeFig.py (no programmatic test to port)
- [x] _circ_smooth.py
- [x] _clans.py
-  _config.py (no test to port)
- [x] _constants.py (no test to port)
- [x] _db.py
- [x] _dbm.py
- [x] _dbp.py
- [x] _dbv.py
- [x] _delay.py
- [x] _DocumentNTF.py
- [x] _dsclansNTF.py
- [x] _ds_f1f2.py
- [x] _ds_freq.py
- [x] _ds_hann.py
- [x] _ds_optzeros.py
- [x] _ds_quantize.py
- [x] _ds_synNTFobj1.py
- [x] _evalF0.py
- [x] _evalF1.py
- [x] _evalMixedTF.py
- [x] _evalRPoly.py
- [x] _evalTF.py
- [x] _evalTFP.py
- [x] _figureMagic.py
-  _frespF1.py (no test)
- [x] _impL1.py
- [x] _infnorm.py
- [x] _l1norm.py
- [x] _logsmooth.py
- [x] _lollipop.py
- [x] _mapABCD.py
- [x] _mapCtoD.py
- [x] _mapQtoR.py
- [x] _mapRtoQ.py
- [x] _mod1.py
- [x] _mod2.py
- [x] _nabsH.py
- [x] _padb.py
- [x] _padl.py
- [x] _padr.py
- [x] _padt.py
- [x] _partitionABCD.py
- [x] _peakSNR.py
- [x] _PlotExampleSpectrum.py
- [x] _plotPZ.py
- [x] _plotSpectrum.py
- [x] _predictSNR.py
- [x] _pulse.py
- [x] _realizeNTF.py
- [x] _realizeNTF_ct.py
- [x] _rms.py
- [x] _rmsGain.py
- [x] _scaleABCD.py
- [x] _simulateDSM.py
- [x] _simulateDSM_python.py
- [x] _simulateSNR.py
- [x] _sinc_decimate.py
- [x] _SIunits.py
- [x] _stuffABCD.py
- [x] _synthesizeChebyshevNTF.py
- [x] _synthesizeNTF.py
- [x] _synthesizeNTF0.py
- [x] _synthesizeNTF1.py
- [x] _test_dsdemo.py
- [x] _thermometer.py
- [x] _undbm.py
- [x] _undbp.py
- [x] _undbv.py
- [x] _utils.py
- [x] _zinc.py
